services:
  splunk:
    image: splunk/splunk:9.1.2
    platform: linux/amd64
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "BlueForge2025!"
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - ./scenarios/sc-001-ransomware/logs:/var/log/blueforge:ro
    networks:
      - blueforge-net

networks:
  blueforge-net:
    driver: bridge