version: '3.8'

services:
  splunk:
    image: splunk/splunk:latest
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "BlueForge2025!"
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - ./scenarios/sc-001-ransomware/logs:/opt/splunk/etc/apps/blueforge/logs:ro
      - ./siem/splunk/inputs.conf:/opt/splunk/etc/system/local/inputs.conf:ro
    networks:
      - blueforge-net

networks:
  blueforge-net:
    driver: bridge